version: "v3.0"
name: Amazing pipeline xxyz
semaphore_image: standard
blocks:
  - name: "Block 1"
    build:
      prologue:
        commands:
          - echo $SEMAPHORE_JOB_ID
      epilogue:
        commands:
          - echo $SEMAPHORE_JOB_RESULT      
      jobs:
        - name: First job ㍊xy
      
          commands:
            - ls /usr/bin | grep checkout
            - ls /usr/bin/libcheckout
            - cat /usr/bin/libcheckout
            - source /usr/bin/libcheckout
            - which checkout
            - checkout
            - pwd
            - echo "cache restore --key=v1-bundle-$(md5 Gemfile.lock),v1-bundle-"
            - echo "bundle install --path=vendor/bundle"
            - ls -lah
            - env | grep "SEMAPHORE_GIT"
            - env | grep "SEMAPHORE"
            - env
            - echo $SEMAPHORE_PIPELINE_ID
            - echo "First job 1"
            - echo "First job 2"
            - echo "First job 3"
            - cat /proc/cpuinfo
            - ls /
            - echo "test"
            - echo "cache store --key=v1-bundle-$(md5 Gemfile.lock) --path=vendor/bundle"
            
        - name: Looooping 🔁
          commands:
            - which checkout
            - checkout
            - for((i=1;i<=10000;i+=2)); do echo "Welcome $i times"; done
            
        - name: New job
          commands:
            - checkout
            - ls /tmp           
            
  - name: "Block 2 🧝‍♀️"
    build:
      jobs:
        - name: Job from 1st block
          commands:
            - echo $SEMAPHORE_PIPELINE_ID
            - echo "Firsdt job 1"
            - echo "First job 2"
            - echo "First job 3"
            
  - name: "Block  3 🧝‍♂️"
    build:
      jobs:
        - name: Job from 1st block 🦄
          commands:
            - echo $SEMAPHORE_PIPELINE_ID
            - echo "cache restore --key=v1-bundle-$(md5 Gemfile.lock)"
            - echo "First job 1"
            - echo "First job 2"
            - echo "First job 3"
        - name: 2nd job from 1st block
          commands:
            - echo "This is from second job"
            - ls /etc            
            
  - name: "BLock 4"
    build:
      jobs:
        - name: Job from 2nd block
          commands:
            - echo $SEMAPHORE_PIPELINE_ID
            - echo bar2
  - name: "Block 5"
    build:
      jobs:
        - name: Job from 3rdd block
          commands:
            - echo foo3dds
            - echo bar3dddds
